# Travis CI Configuration file
# @link https://travis-ci.org/

language: java
jdk:
  - oraclejdk8
matrix:
  include:
    - jdk: oraclejdk8
      env: DEPLOY=true
cache:
  directories:
    - $HOME/.m2
script:
  # Unit and integration tests are run
  - mvn clean verify
after_success:
  script: "mvn clean dependency:list test install -U"
